import {
  Entity,
  Column,
  PrimaryGeneratedColumn,
  CreateDateColumn,
  UpdateDateColumn,
  ManyToOne,
  JoinColumn,
} from 'typeorm';
import { FileStatus, FileVisibility } from '../files/file.types';
import { User } from './user.entity';

@Entity('file_records')
export class FileRecord {
  @PrimaryGeneratedColumn('uuid')
  id!: string;

  @Column({ type: 'uuid' })
  ownerId!: string;

  /** Entity this file is attached to (e.g. user id for avatar). */
  @Column({ type: 'uuid' })
  entityId!: string;

  /** S3 key; always generated by backend (e.g. users/{userId}/avatars/{uuid}.jpg). */
  @Column({ type: 'varchar', length: 512, unique: true })
  key!: string;

  @Column({ type: 'varchar', length: 128 })
  contentType!: string;

  @Column({ type: 'int', default: 0 })
  size!: number;

  @Column({ type: 'varchar', length: 32, default: FileStatus.PENDING })
  status!: FileStatus;

  @Column({ type: 'varchar', length: 32, default: 'private' })
  visibility!: FileVisibility;

  @CreateDateColumn()
  createdAt!: Date;

  @UpdateDateColumn()
  updatedAt!: Date;

  @ManyToOne(() => User, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'ownerId' })
  owner?: User;
}
